/**
 * Copyright 2026 Rxnel-ysr
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the “Software”), to deal in 
 * the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of 
 * the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR 
 * A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN 
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
"use strict"; import VDOM from "./core/vdom.js"; import { Hooks, Root } from "./core/vdom.hooks.js"; import Memory from "./core/memory.js"; function createSetup(selector = null) { const vdom = new VDOM(new Memory()); const hooks = new Hooks(vdom); vdom.setHooks(hooks); if (typeof selector === "string") { return [hooks.createRoot(selector), vdom, hooks]; } return [vdom, hooks]; } const [vdom, hooks] = createSetup(); const html = vdom.html; const vnode = vdom.vnode.bind(vdom); const getTarget = vdom.getTarget.bind(vdom); const getKey = vdom.getKey.bind(vdom); const updateProps = vdom.updateProps.bind(vdom); const createVNode = vdom.createVNode.bind(vdom); const renderVNode = vdom.renderVNode.bind(vdom); const cleanupVNode = vdom.cleanupVNode.bind(vdom); const RenderVDOM = vdom.RenderVDOM; const patch = vdom.patch.bind(vdom); const registerVdom = vdom.registerVdom.bind(vdom); const pushJob = vdom.pushJob.bind(vdom); const executeJobs = vdom.executeJobs.bind(vdom); const resetContext = hooks.resetContext.bind(hooks); const useState = hooks.useState.bind(hooks); const useEffect = hooks.useEffect.bind(hooks); const useMemo = hooks.useMemo.bind(hooks); const useRef = hooks.useRef.bind(hooks); const createRoot = hooks.createRoot.bind(hooks); const resets = hooks.resets.bind(hooks); const getCurrentHookNode = hooks.getCurrentHookNode.bind(hooks); const destroy = hooks.destroy.bind(hooks); const comp = hooks.comp.bind(hooks); const allocate = hooks.allocate.bind(hooks); const orphan = hooks.orphan.bind(hooks); const overwrite = hooks.overwrite.bind(hooks); const triggerRerender = hooks.triggerRerender.bind(hooks); const getData = hooks.getData.bind(hooks); const bulkSetState = hooks.bulkSetState.bind(hooks); const hmr = hooks.hmr.bind(hooks); export { default as Memory } from './core/memory.js'; export * from './extensions/router.js'; export * from './helper/helper.js'; export { VDOM, Hooks, vdom, hooks, html, vnode, getTarget, getKey, updateProps, createVNode, renderVNode, cleanupVNode, RenderVDOM, patch, registerVdom, pushJob, executeJobs, resetContext, useState, useEffect, useMemo, useRef, createRoot, resets, getCurrentHookNode, destroy, comp, allocate, orphan, overwrite, triggerRerender, getData, bulkSetState, hmr, createSetup }
